### ISSUE TITLE
Camera Unavailable

### ISSUE THREAD

**Issue by 1800Zeta** [RenierM26/ha-ezviz#10]
The integration is no longer working. I am seeing the following error and unable to connect to the camera:

```
Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:31
Integration: Ezviz Cloud (documentation)
First occurred: 11:24:08 (3 occurrences)
Last logged: 11:24:26

Unexpected error fetching ezviz_cloud data: 32
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.EzvizClient.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 266, in load_cameras
    camera.load()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 34, in load
    if self._switch[DeviceSwitchType.AUTO_SLEEP.value] != True:
KeyError: 32
```

My account doesn't have MFA, in my configuration.YAML I have the following:

```
ezviz_cloud:
  username: prefix@domain
  password: Password
  cameras:
    243798428:
      username: admin
      password: PWD
```

Any ideas?
Thanks

**Comment by RenierM26** [comment]
Hi There,

Think solved the issue in the latest release (0.0.2.5). Would you mind testing?

**Comment by 1800Zeta** [comment]
Works thank you. Had to set the lovelace card to use Live camera view rather than auto but working now. Thank you

**Comment by pete-leese** [comment]
I have updated to 0.2.5 and my live camera preview no longer work with 0.0.2.5.

I have EZViz DB1 doorbelll

Logger: libav.rtsp
Source: components/stream/worker.py:240
First occurred: 22:50:32 (2 occurrences)
Last logged: 22:50:35

Error parsing AU headers
nal size exceeds length: 4475 1445

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:609
Integration: Camera (documentation, issues)
First occurred: 22:50:20 (3 occurrences)
Last logged: 22:50:42

Error requesting stream: Camera is off

**Comment by RenierM26** [comment]
Hi pete-leese, 

1) Could you please check the "RTSP stream" attribute on your camera? You can test it via VLC player.

2) It could also be that your camera reports a different status code when online. (Hass thinks it's off). Would you be able to run the pyezviz (the underlying API) and show me the output?  https://github.com/RenierM26/py-ezviz

pyezviz -u username@domain.com -p "password" devices status

**Comment by pete-leese** [comment]
Running command outlined in point 2 produces:

Login error: Captcha required 

I copied the string for the RTSP value into VLC and it was able to stream from my camera.

Copied this from developer tab in HA.

model_name: DB1
brand: Ezviz
motion_detection: true
sw_version: V5.2.4 build 200220
upgrade_available: 0
privacy: false
sleep: false
audio: true
ir_led: true
state_led: true
follow_move: null
alarm_schedules_enabled: false
alarm_sound_mod: MUTE_MODE
encrypted: true
local_ip: XXX.XXX.XXX.XXX
battery_level: 0
PIR_Status: 0
detection_sensibility: 6
Last alarm triggered: Today 19:27:07
Last alarm image url: https://ieu.ezvizlife.com/v3/alarms/pic/get?fileId=xxxxxxxxxxx
RTSP stream: rtsp://xxxx:xxxx@xxx.xxx.xxx.xxxx:554None
friendly_name: Front Door
entity_picture: /api/camera_proxy/camera.front_door?token=xxxx
supported_features: 2

Also can see same error relating to Captcha too in logs
2021-01-24 22:09:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry pete@vr6oc.com for ezviz_cloud
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
ezviz_client = await hass.async_add_executor_job(
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/ezviz_cloud/__init__.py", line 146, in _get_ezviz_client_instance
ezviz_client.login()
File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 308, in login
self._login()
File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 78, in _login
raise PyEzvizError("Login error: Incorrect Captcha code")
pyezviz.client.PyEzvizError: Login error: Incorrect Captcha code

**Comment by pete-leese** [comment]
Do you need anymore info to help debug @RenierM26 ?

**Comment by thangman22** [comment]
I found on API it return status 2 instead of 1

**Comment by RenierM26** [comment]
Hi @pete-leese,

Your username and password could be incorrect or you might need to open the https://i.ezvizlife.com/ website and login.

The capta error could be a once off. If there are too many failed login attempts, then you'll need to open the website and login. There after the addon should word. Looks like ezviz blocks access to your login after too many failed login attempts and then requires a capcha code

**Comment by RenierM26** [comment]
Hi @thangman22,

Status code 2 is usually returned if your device is offline.

**Comment by thangman22** [comment]
> Hi @thangman22,
> 
> Status code 2 is usually returned if your device is offline.

But it is online

**Comment by pete-leese** [comment]
I updated integration to the latest release and it works.

**Comment by pete-leese-dlg** [comment]
I speak to soon :) 

The Lovelace camera preview no longer works and logs report 

Logger: homeassistant.components.camera
Source: components/camera/__init__.py:609 

I can see all entities in the developer tools and when I copy / paste RTSP string into VLC player it plays OK. 

I ran pyezviz as suggested earlier on and now reporting status code 2 - even though It is online, connected to my Wifi and recording OK.

      serial        name status device_category device_sub_category  sleep  privacy  audio  ir_led  state_led       local_ip  local_rtsp_port detection_sensibility battery_level  PIR_Status
0  XXXXXXX  Front Door      2       BDoorBell                 DB1  False    False   True    True       True  192.168.XX.XX               0                     6             0           0

**Comment by 1800Zeta** [comment]
I am seeing similar, logs report it's offline, despite it being on and the EzViz app sending notifications etc. Lovelace preview not working either.

**Comment by pete-leese** [comment]
I speak to soon :)

The Lovelace camera preview no longer works and logs report

Logger: homeassistant.components.camera
Source: components/camera/init.py:609

I can see all entities in the developer tools and when I copy / paste RTSP string into VLC player it plays OK.

I ran pyezviz as suggested earlier on and now reporting status code 2 - even though It is online, connected to my Wifi and recording OK.

```
      serial        name status device_category device_sub_category  sleep  privacy  audio  ir_led  state_led       local_ip  local_rtsp_port detection_sensibility battery_level  PIR_Status
0  XXXXXXX  Front Door      2       BDoorBell                 DB1  False    False   True    True       True  192.168.XX.XX               0                     6             0           0
```

**Comment by pete-leese** [comment]
Seems to be ok with the latest version.

**Comment by RenierM26** [comment]
Hi @pete-leese ,

Thank you for confirming.
