### ISSUE TITLE
Error al conectar

### ISSUE THREAD

**Issue by vtb77** [RenierM26/ha-ezviz#115]
Hello:

I have several days with the following error and I can not solve it. Can you help me? Thank you

![Sin título](https://user-images.githubusercontent.com/71189405/170106793-71fd655e-8aa2-48b8-9041-17c5b35293b6.png)

![Sin título 1](https://user-images.githubusercontent.com/71189405/170106871-ea01b0d7-fd06-4007-b36e-11c386bbeb22.png)

**Comment by RenierM26** [comment]
Hi @vtb77, 

Is this still a problem?

**Comment by vtb77** [comment]
Hello:

Now it works correctly for me. Thanks for the good work.
