### ISSUE TITLE
Unable to prepare setup for platform ezviz_cloud.camera

### ISSUE THREAD

**Issue by lucafwlavoro** [RenierM26/ha-ezviz#118]
Hi, I installed this repository a long time ago and I must say that it never gave me any problems.
Instead, recently (not knowing if it depends on an HA update) the following error appears:

Unable to prepare setup for platform ezviz_cloud.camera: Platform not found (cannot import name 'CONF_USE_WALLCLOCK_AS_TIMESTAMPS' from 'homeassistant.components.stream' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/stream/ __init__.py)).

Also compile the configuration.yaml file as suggested, the file verification also fails:

  - platform: ezviz_cloud
    username: "xxxxxxxx@gmail.com"
    password: "xxxxxxxx"
    cameras:
      G61555105:
        username: admin
        password: xxxxxxxx
      G80269259:
        username: admin
        password: xxxxxxx

Note:
right now i have this version 
Home Assistant Core 2022.5.4

**Comment by RenierM26** [comment]
Hi @lucafwlavoro, your home assistant version is too old.

cannot import name 'CONF_USE_WALLCLOCK_AS_TIMESTAMPS. -> This was added in a later release. (It think around August but could be wrong)

If you need to use an older Home assistant version then you'll need to run an older version of this integration.
