### ISSUE TITLE
Error: There are multiple cookies with name, 'AS_SessionID'

### ISSUE THREAD

**Issue by short4bmoney** [RenierM26/ha-ezviz#12]
Issue that I'm unsure how to troubleshoot in one of the underlying python libraries.

> Logger: homeassistant.config_entries
> Source: custom_components/ezviz_cloud/__init__.py:146
> First occurred: 10:51:09 AM (1 occurrences)
> Last logged: 10:51:09 AM
> 
> Error setting up entry `<Email removed>` for ezviz_cloud
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
>     ezviz_client = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 146, in _get_ezviz_client_instance
>     ezviz_client.login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 308, in login
>     self._login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 85, in _login
>     self._csrfToken = self._session.cookies['AS_SessionID']
>   File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 328, in __getitem__
>     return self._find_no_duplicates(name)
>   File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 394, in _find_no_duplicates
>     raise CookieConflictError('There are multiple cookies with name, %r' % (name))
> requests.cookies.CookieConflictError: There are multiple cookies with name, 'AS_SessionID'
>

**Comment by RenierM26** [comment]
Hi short4bmoney,

It look like you have multiple ezviz logins on your ha instance:

requests.cookies.CookieConflictError: There are multiple cookies with name, 'AS_SessionID'

1) Could you please check that you don't have any account login details in your config.yaml file? By ezviz account i'm referring to your email login with password. 
2) Are you using the correct country code?  You can login to https://i.ezvizlife.com/ to find your country code. It only redirect to the correct country domain after login though. (You'll need Internet explorer or safari)

**Comment by RenierM26** [comment]
Hi There,

I have added some code to handle exceptions on duplicate AS_SessionID cookies. Could you please try the latest release?

0.0.2.6 Should fix your problem.

**Comment by short4bmoney** [comment]
I updated to 0.0.2.6 and Supervisor 2021.1.5 to fix the security vulnerability. I made sure my configuration.yaml file is correct, given that I have another camera from a different platform:

```yaml
stream:
ffmpeg:
camera:
  - platform: ffmpeg
    name: Living Room
    input: -rtsp_transport http -i rtsp://hassio:tinker@192.168.0.49/live
    extra_arguments: -pred 1 -q:v 2

ezviz_cloud:
  cameras:
    E81680149:
      username: admin
      password: !secret ezviz_cam1_code

```

I also re-installed the EZVIZ Cloud integration, and updated my region to **usa** as shown in the app on my profile. Yet I still get login errors for the API. Maybe I should keep the default `eu` region?

> Error setting up entry `<email removed>` for ezviz_cloud

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
>     conn = connection.create_connection(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name does not resolve
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
>     httplib_response = self._make_request(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
>     conn = self._new_conn()
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8efef340>: Failed to establish a new connection: [Errno -2] Name does not resolve
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
>     resp = conn.urlopen(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
>     retries = retries.increment(
>   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='usaauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8efef340>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 64, in _login
>     req = self._session.post("https://" + self._AUTH_DOMAIN + API_BASE_TLD + API_ENDPOINT_AUTH,
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='usaauth.ezvizlife.com', port=443): Max retries exceeded with url: /doLogin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8efef340>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
>     result = await component.async_setup_entry(hass, self)  # type: ignore
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
>     ezviz_client = await hass.async_add_executor_job(
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/ezviz_cloud/__init__.py", line 146, in _get_ezviz_client_instance
>     ezviz_client.login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 312, in login
>     self._login()
>   File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 92, in _login
>     raise PyEzvizError("Can not login to API")
> pyezviz.client.PyEzvizError: Can not login to API

**Comment by RenierM26** [comment]
Hi There @short4bmoney ,

It looks like a problem with the region code. For usa I believe it should be just  us and not usa

**Comment by RenierM26** [comment]
Hi @short4bmoney,

Did it work? May I close this issue?

**Comment by short4bmoney** [comment]
Hi, and yes! After updating to the latest version in HACS the stream loads as expected. Thank you for your help!
