### ISSUE TITLE
Config success even login is error

### ISSUE THREAD

**Issue by thangman22** [RenierM26/ha-ezviz#14]
I try to put the wrong username and password but the configuration can be finished. I try to fig the code but I'm not good with has flow and Python

**Comment by RenierM26** [comment]
Hi @thangman22,

Thank you for the feedback. I'll work on a check for this.

**Comment by RenierM26** [comment]
Hi @thangman22,

I have fixed the login check in the latest release. It now gives a "authentication" error if the wrong login details are used when setting up the integration.
