### ISSUE TITLE
Region list?

### ISSUE THREAD

**Issue by MeighenHouse** [RenierM26/ha-ezviz#17]
My region is Canada in the app, but if I set the region to "ca" or "Canada" I get login errors about the API.

If I leave the region as "eu" it appears to login but the error message is "Unexpected error fetching ezviz_cloud data: (Impossible to load the devices..." etc.

Do you have a list for what the region code should be?

**Comment by RenierM26** [comment]
Hi @MeighenHouse ,

At the moment the easiest way to check is to open https://ieu.ezvizlife.com and complete the login process. After login the url will change to the correct country. This page only works on IE and Safari.

**Comment by MeighenHouse** [comment]
Thanks. Turns out for Canada you just use "us". The camera shows as an entity now, but stream doesn't load.

When I get some time I'll try to figure out what I did wrong.

**Comment by RenierM26** [comment]
Hi @MeighenHouse,

The "auto" picture entities only work if the integration ffmpeg options are blank. Or you could change the picture element (lovelace) option from "auto" to live.
