### ISSUE TITLE
 input_boolean.pir_triggered	never updates

### ISSUE THREAD

**Issue by pete-leese** [RenierM26/ha-ezviz#18]
I notice that when motion has been triggered that the 

input_boolean.pir_triggered never updates, and always stays 'off'

**Comment by RenierM26** [comment]
Hi @pete-leese,

Please use the "motion_sensor" attribute for now. You can use a template sensor for this at the moment.

Example binary sensor template. Just change the names.

  - platform: template
    sensors:
      ezviz_backyard_pir:
        unique_id: EZVIZPIRTEMPL1
        friendly_name: "Ezviz Backyard PIR"
        device_class: motion
        value_template: "{{ state_attr('camera.backyard_camera_1', 'motion_sensor') }}"

**Comment by pete-leese** [comment]
Mmm syntax doesn’t seem right here. I’ll wait until the next release :)

**Comment by RenierM26** [comment]
Hi @pete-leese,

The latest version has a motion detection entity that should work (camera name.Motion_Trigger). 

The "PIR" sensor I think will only work with the non-camera sensors.
