### ISSUE TITLE
Could not set the switch, maybe a permission issue ?: Got %s : %s)', '200', '{"resultCode":"-1"}

### ISSUE THREAD

**Issue by Christianb233** [RenierM26/ha-ezviz#20]
Hello RenierM26,
So first of all, I thank you very much for your code which has enable to have more control on my CTQ6C cam into Home Assistant.
All the commands seem to work except the 2 first icon"switch.set" (linked with the alarm I imagine) with the following error : 

Could not set the switch, maybe a permission issue ?: Got %s : %s)', '200', '{"resultCode":"-1"}

Do you know how can I solve this problem ?
I thank you in advance for your help !

**Comment by RenierM26** [comment]
Hi @Christianb233,

We have fixed an issue with the switches in the latest release. All switches should now work. Could you please test?

**Comment by Christianb233** [comment]
Hi @RenierM26 , 
Thank you very for your help ! it works well, great :-)

**Comment by Christianb233** [comment]
Hi @RenierM26 , 
Thank you very for your help ! it works well, great :-)
