### ISSUE TITLE
PTZ works?

### ISSUE THREAD

**Issue by Francisk0** [RenierM26/ha-ezviz#21]
Hi, I try to connect the camera, but when login in integrations only have data of those ones.
I can add stream with code:
camera:
  - platform: ffmpeg
    name: BARBACOA
    input: rtsp://admin:XXXXXXXX@192.168.XXX.XXX:554

How to can use PTZ service?
How can add PIR SENSOR?
Regards and thanks for your work.

**Comment by RenierM26** [comment]
![image](https://user-images.githubusercontent.com/66512715/107882157-73dcf900-6ef0-11eb-92d6-7f65b986b4d3.png)

**Comment by RenierM26** [comment]
Hi @Francisk0 ,

That service should work for PTZ. The yaml config entries are only used for steaming and you can find an example in the readme file. (Uses a new domain - Not under cameras as the old integration.)

**Comment by RenierM26** [comment]
Hi @Francisk0 ,

You'll see there is also a binary motion_trigger sensor you can use to indicate motion. Motion detection needs to be enabled on the cam for this to work.

**Comment by Francisk0** [comment]
Hi, 
I have the service ezviz_cloud.ezviz_ptz but I don´t have the service ezviz.ezviz_ptz

**Comment by RenierM26** [comment]
Hi @Francisk0,

That's the correct service name (ezviz_cloud.ezviz_ptz). Sorry the pic above is from my dev environment where I'm working on a pull request for the official component with a different domain name. 

Apologies for the confusion.

**Comment by Francisk0** [comment]
Hi @RenierM26,
I try with that service, but not found. I can't move the camera

**Comment by Pettirosso2022** [comment]
ezviz_cloud.ezviz_ptz not work

**Comment by miitiicoo** [comment]
work! but use:
service: ezviz.ptz   
NOT USE service: ezviz_cloud.ezviz_ptz
