### ISSUE TITLE
Not working after updating 0.0.3.5

### ISSUE THREAD

**Issue by indoor25** [RenierM26/ha-ezviz#28]
Good afternoon, after updating to version 0.0.3.5, it stopped working. Gives an error message:
Logger: homeassistant.config_entries
Source: custom_components/ezviz_cloud/__init__.py:149
First occurred: 15:34:56 (1 occurrences)
Last logged: 15:34:56

Error setting up entry indoo*****@gmail.com for ezviz_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 91, in async_setup_entry
    ezviz_client = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/__init__.py", line 149, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 81, in _login
    json_result = req.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

uninstalled, reinstalled, doesn't work. What could be the reason? Before the update everything worked.
thank you for your work

core-2021.2.3
supervisor-2021.02.9
Docker | 20.10.2

**Comment by RenierM26** [comment]
HI @indoor25,

The error stack shows that there is a login problem. You you please check your username, password and region under integrations?

File "/config/custom_components/ezviz_cloud/init.py", line 149, in _get_ezviz_client_instance
ezviz_client.login()
File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
self._login()

**Comment by indoor25** [comment]
I enter the username and password for the application. I checked this data 10 times, the application enters under this data. The default region is eu (Ukraine). I suspect that something happened in HA itself, even a rollback to previous versions does not help

**Comment by indoor25** [comment]
I don't know what happened, but after the tenth time of installing and uninstalling the integration it worked, the login and password are the ones that I entered before.
Thanks again for your work.

**Comment by indoor25** [comment]
It worked for about 3 hours, and all sensors and switches became inaccessible. I reinstall and nothing helps, the error is the same as above, registration will not go through.
File "/config/custom_components/ezviz_cloud/__init__.py", line 149, in _get_ezviz_client_instance
    ezviz_client.login()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 480, in login
    self._login()

installed EZVIZ PC Studio Software, authorization takes place the first time. I don't understand what the problem is

**Comment by RenierM26** [comment]
Hi @indoor25 ,

You could try increasing the timeout under the integration options?

**Comment by indoor25** [comment]
increased, overloaded - did not help
![12334png](https://user-images.githubusercontent.com/76408736/108587004-174b6500-735a-11eb-86f0-0435f8690c45.png)

**Comment by RenierM26** [comment]
Hi @indoor25,

You can also try to login useing this page : https://ieu.ezvizlife.com 
Sometimes ezviz forces a capcha check after a couple of invalid logins. I have one API to figure out before I can change the login portion of the API to the token based login approach. (with support for MFA)

**Comment by indoor25** [comment]
The problem is that if I, using internet explorer, go to this address, then I get a 403 access denied error. If I connect via VPN (French server), I can register and log into my account. No redirection to the required server occurs. I myself live in Ukraine

**Comment by RenierM26** [comment]
Hi @indoor25 ,

The region url is the reason why this isn't working. Could be that ukraine recently got their own server? 

We  just need to determine the region. Could you try: https://i.ezvizlife.com ? It might redirect after login. (Will go to us page first)

**Comment by indoor25** [comment]
Something strange is happening with my router, or with the provider. Connecting directly to the provider's cable, the page opens, but if I connect through a router (Mikrotik) I get 403. But sometimes the page becomes available through the router, without any action on my part. At such a moment, I can configure the integration and everything works, but after a while access disappears again ..... :(

**Comment by indoor25** [comment]
The problem has been clarified, but not completely. The site itself blocks me by IP. Why is it not clear. But, when I change my ip address, access opens. Yesterday I changed it several times until I got access, it works for a day.
