### ISSUE TITLE
Switch CAMERA.SLEEP ON is ok but broke connection

### ISSUE THREAD

**Issue by elasgi** [RenierM26/ha-ezviz#30]
Hello the switch camera.sleep work when the camera is on and when I want to turn in sleep mode.

But in this case all the switch and the sensor of all cameras become indisponible.

And I can't turn this switch off, because this switch and over all is indisponible.

For information the service : ezviz_cloud.ezviz_wake_device doesn't work.

Anyone have a same problem?

Sorry for my bad english.

**Comment by tastopesato** [comment]
Same issue to me.

**Comment by RenierM26** [comment]
Hi @elasgi  and @tastopesato,

Please increase the timeout on the integration options to 30.

It seems as though the cameras take much longer to respond when sleeping.

**Comment by tastopesato** [comment]
Increasing timeout to 30 sec. works. I tried 20 sec also, and it works. However, i remember setting sleep mode thru service call was reacting much more fast.
Now, when i set privacy from off to on, the switch go in "on position", and after few seconds return to "off position"; it sets itself to "on position" again only after 20 seconds.

**Comment by elasgi** [comment]
Thanks it work now.

Congratulations for your integration, and for your update which IS more ans more stable and easy.

**Comment by RenierM26** [comment]
@tastopesato ,

The switch basically runs the "set switch" service. The entity switch then resets until hass polls the state from ezviz. 

Basically you just need to wait a few seconds to see if the change was successful. It's similar to how you would use the "set switch" service and then wait before the attribute updates. 

I have readded the "set switch" service in the latest release although I don't think it will be used. The built in hass set switch service should work on the switches as well.
