### ISSUE TITLE
v0.0.4.4 No entities

### ISSUE THREAD

**Issue by AlessandroTischer** [RenierM26/ha-ezviz#38]
Hello, I was able to set up Ezviz integration, log in my account (I'm from Italy, so it's based in EU) and add my cameras:

![image](https://user-images.githubusercontent.com/23379317/109725642-bae61200-7bb1-11eb-8078-36646e74435a.png)

Anyways, I get no entities:

![image](https://user-images.githubusercontent.com/23379317/109725674-c6d1d400-7bb1-11eb-9274-ea4694096c62.png)

Since here https://github.com/RenierM26/ha-ezviz/issues/36#issuecomment-784123018 it was said they could see services, I specify that I don't:

![image](https://user-images.githubusercontent.com/23379317/109725612-ae61b980-7bb1-11eb-94bb-80fa73d1325f.png)

Finally, on reboot I get this log in loop:

`Unexpected error fetching ezviz_cloud data: Can't gather proper data. Max retries exceeded.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 320, in load_cameras
    devices = self._get_all_device_infos()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 359, in _get_all_device_infos
    devices = self._get_page_list()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 778, in _get_page_list
    return self._api_get_pagelist(
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 136, in _api_get_pagelist
    return self._api_get_pagelist(page_filter, json_key, max_retries + 1)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 117, in _api_get_pagelist
    raise PyEzvizError("Can't gather proper data. Max retries exceeded.")
pyezviz.client.PyEzvizError: Can't gather proper data. Max retries exceeded.`

`Config entry 'alessandrotischer' for ezviz_cloud integration not ready yet. Retrying in 5 seconds
Config entry 'alessandrotischer' for ezviz_cloud integration not ready yet. Retrying in 10 seconds
Config entry 'alessandrotischer' for ezviz_cloud integration not ready yet. Retrying in 20 seconds
Config entry 'alessandrotischer' for ezviz_cloud integration not ready yet. Retrying in 40 seconds
Config entry 'alessandrotischer' for ezviz_cloud integration not ready yet. Retrying in 80 seconds`

I've also seen here https://github.com/RenierM26/ha-ezviz/issues/36#issuecomment-789369882 that removing and adding back the camera using the default app-given name for the camera serial could help, but it's not my case:

![image](https://user-images.githubusercontent.com/23379317/109785003-f281a800-7c0b-11eb-8096-b77e417ebcbb.png)

**Comment by nguyenbabao** [comment]
entity is name of camera in app, don't need add camera  to integration
<a href="https://imgur.com/iuj5utV"><img src="https://i.imgur.com/iuj5utV.jpg" title="source: imgur.com" /></a>

**Comment by AlessandroTischer** [comment]
> entity is name of camera in app, don't need add camera to integration
> [![](https://camo.githubusercontent.com/5ff3b320eb453fb9c3cff7861ff6b8673a7a675db98a8f2de32e0f933a0d7f42/68747470733a2f2f692e696d6775722e636f6d2f69756a357574562e6a7067)](https://imgur.com/iuj5utV)

![image](https://user-images.githubusercontent.com/23379317/109794102-ce2ac900-7c15-11eb-808d-c97b4e6992de.png)

![image](https://user-images.githubusercontent.com/23379317/109794204-eb5f9780-7c15-11eb-8d3e-a1e28bf72592.png)

I tried deleting the Integration and re-adding it, with my mail instead of the username as you did, but still no entities appeared...

**Comment by AlessandroTischer** [comment]
Ok, I solved creating a new account. I don't know why, but it works...

**Comment by moh-Brent** [comment]
Did you set it up with a different email or the same?

**Comment by AlessandroTischer** [comment]
> Did you set it up with a different email or the same?

At first I created a new account with different email and different username
Then I realized that the only reason I couldn't see cams with the original account was that it required two steps verification. Once removed it, I was able to import everything with the original account.
