### ISSUE TITLE
Region get from https://ieu.ezvizlife.com/

### ISSUE THREAD

**Issue by nguyenbabao** [RenierM26/ha-ezviz#39]
when login, http will change for region of you
example: i live in vietnam, i login and http will change to  https://isgp.ezvizlife.com => region of me is "sgp"

My communication is not good, it took me many days to learn this problem: D. Tks Renier :D

**Comment by RenierM26** [comment]
Hi @nguyenbabao,

Thank you for the info. I have added a function in the latest release to log the correct region and fix it for you. Should work on all the api**.ezvizlife.com endpoints at least.
