### ISSUE TITLE
Service for change privacy mode

### ISSUE THREAD

**Issue by ocimin** [RenierM26/ha-ezviz#4]
Hi,
thanks a lot for your work!
Is it possible activate/disactivate privacy mode of the camera? Something like camera.ezviz_switch_privacy_on on old integration.
Thanks!

**Comment by RenierM26** [comment]
Hi ocimin,

You should be able to set privacy via the "ezviz_cloud.ezviz_switch_set" service.

Jou can use the service example under the developer menu.

The name for the specific switch should be PRIVACY
The switch names have to be in uppercase.

**Comment by RenierM26** [comment]
The first line Enable or disabled based on the 0 or 1.

To disable:
Enable: 0

To enable
Enable: 1

This should work. Or do you have another reason in mind for a seperate service?

I still need to improve on the nameing to make this more logical to the user.

**Comment by ocimin** [comment]
Great, it's work!
Sorry for the stupid question but I'm new on the platform and I have to familiarize with its philosophy.
I have another question on the motion detection. I can enable/disable it with, for example, camera.disable_motion_detection service. But when the parameter is enable there is a row "motion_detection: true" in attributes of the camera entity, when not, the attribute motion_detection disappear. Is it normal? Why isn't became "motion_detection: false"? I ask for any scripts that need to use that information
Thanks again.

**Comment by mindtripper** [comment]
> Great, it's work!
> Sorry for the stupid question but I'm new on the platform and I have to familiarize with its philosophy.
> I have another question on the motion detection. I can enable/disable it with, for example, camera.disable_motion_detection service. But when the parameter is enable there is a row "motion_detection: true" in attributes of the camera entity, when not, the attribute motion_detection disappear. Is it normal? Why isn't became "motion_detection: false"? I ask for any scripts that need to use that information
> Thanks again.

I can confirm the same behavior that @ocimin mentions above.
`camera.enable_motion_detection` the attribute motion_detection: true is shown.
`camera.disable_motion_detection` there is no attribute motion_detection at all.

Keep up the awesome progress on this component!

**Comment by RenierM26** [comment]
Hi guys, 

I make use of a standard hassio attribute and it looks like it "disappears" when the value isn't true. I see other integrations make use of the "is recording" property for this. I'll test is out and see what the results are.

**Comment by RenierM26** [comment]
Hi Mindtripper and Ocimin,

I've added "is recording" property to the latest release (0.0.2.5). The camera status will change to recording when motion detection is enabled and "idle" when disabled. This should make automation easier.

Would you mind testing?

**Comment by mindtripper** [comment]
> Hi Mindtripper and Ocimin,
> 
> I've added "is recording" property to the latest release (0.0.2.5). The camera status will change to recording when motion detection is enabled and "idle" when disabled. This should make automation easier.
> 
> Would you mind testing?

Hi @RenierM26 

Did a quick test. The camera state changes to "recording" when motion is detected.
Will create an automation using this feature. As this will be a great addition.

Keep up the awesome work.

/Christer


/Christer

**Comment by RenierM26** [comment]
Excellent. Thank you for the feedback!

**Comment by mindtripper** [comment]
I've done some more testing, and found that if the camera state is "recording" and I put it to sleep. The state does not return to idle, but keeps the "recording" state.

**Comment by ocimin** [comment]
The same with privacy attribute but I think is normal. If I understand correctly "Recording" and "Idle" are synonyms respectively for "motion_detection: true" and "motion_detection: false" (that don't exist) regardless of the state of the other attributes. Is it right?
