### ISSUE TITLE
Wrong API_BASE_TLD

### ISSUE THREAD

**Issue by Shlyakhoff** [RenierM26/ha-ezviz#44]
Hi!
I can't pass authentification because in Russia there is another api domain - ezvizru.com instead of ezvizlife.com. Could you please add to the integration the ability to change API_BASE_TLD

Below are the links through I successfully log in to my account:
https://rusauth.ezvizru.com/
https://apirus.ezvizru.com/

**Comment by RenierM26** [comment]
Hi @Shlyakhoff,

I have added support for other regions to the latest release. It should work if you type in the full API url: apirus.ezvizru.com when setting up the integration.

**Comment by Shlyakhoff** [comment]
Hi @RenierM26 
All is working fine, thank you! You have done great job!

**Comment by RenierM26** [comment]
@Shlyakhoff,

It's a pleasure. Thank you for confirming.
