### ISSUE TITLE
Password in plaintext on config/.storage/core.config_entries

### ISSUE THREAD

**Issue by tyron** [RenierM26/ha-ezviz#47]
I don't recall this behaviour from previous versions (~0.3). I just noticed that with the new auto-discovery, the plaintext password is now stored on `config/.storage/core.config_entries`. This is not ideal, since one typical process is to store everything under config in a GitHub repo (except some files like `secrets.yaml`).

Is it possible to revert to the previous behaviour?

**Comment by RenierM26** [comment]
Hi @tyron,

This is the way hassio works. YAML config is depreciated.

I'm busy working on storing the token and refresh token only. But this could be used to login to the API if accidentally exposed.
