### ISSUE TITLE
Invalid authentication

### ISSUE THREAD

**Issue by maskmatt** [RenierM26/ha-ezviz#48]
Hi,
everyhting worked fine until yesterday (or at least yesterday I noticed this), then some entities of my cameras where not available anymore (last alarm pic, last triggered and son on)

I decided to clean everything: delete integration, delete repository on hacks, restart hassio and then start again

now when i tried to insert credential i get error: Invalid authentication

![iz](https://user-images.githubusercontent.com/76448822/112974113-5edfc080-9152-11eb-861d-242eac901d01.png)

**Comment by mindtripper** [comment]
Got similar issue. HA logs are spammed with "Too many failed logins".

Same goes for pyezviz. Which reports "Too many failed logins. Open API url in IE and enter Captcha code".

Tried the IE trick logging in and supplying captcha, but it does not help.
https://euauth.ezvizlife.com/signIn asks for captcha every time I try to access it.

Note: Login to https://euauth.ezvizlife.com/signIn is successful when supplying captha (every time).

**Comment by hdjweb** [comment]
I have the same error because ezviz added captcha verification, but i tryed to replace server with euauth.ezvizlife.com but i have unexcept error

**Comment by 39domotica** [comment]
I have the same error
