### ISSUE TITLE
Error while setting up ezviz_cloud platform for camera

### ISSUE THREAD

**Issue by polemopouli** [RenierM26/ha-ezviz#50]
Suddendly I lost the video entity from hassio. I investigated a bit and found this error. If I manually edit the camera.py file and make the variables with the camera username and password static it works. I tried reinstalling the integration and do everything from the start but same thing happens. Any ideas?

`Error while setting up ezviz_cloud platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ezviz_cloud/camera.py", line 123, in async_setup_entry
    camera_username = conf_cameras.data[CONF_USERNAME]
KeyError: 'username'`

**Comment by RenierM26** [comment]
Hi @polemopouli,

The only reason this will hapen is if the username is missing in your hassio config. (which should be impossible)

Have a look in this file. You could try manually deleting all the ezviz entries. (Just be careful when editing this file)
\config\.storage\core.config_entries

**Comment by polemopouli** [comment]
I found some time today and I started investigating. It is weird so I will try to explain it in steps. Here it goes...

On my ezviz account I have 2 cameras. One that a want integrated to hass and one that I don't.

I delete all ezviz entries inside core.config_entries and import the camera credentials through configuration.yaml in order not to waste time.

I restart hass and the camera works perfect. I restart hass again without any problems, the camera works great.

I have a new device discoveres message about the camera that I haven't imported so I ignore the camera in integrations  in order not to see it.

Everything still works great. But now if I restart hass the camera never works again until I do all the proceedure from the beginning.

**Comment by RenierM26** [comment]
Hi @polemopouli,

Found and fixed the issue. Could you please try the latest release? v0.0.5.9

**Comment by polemopouli** [comment]
Problem is solved :)

**Comment by RenierM26** [comment]
Thank you for the feedback!
