### ISSUE TITLE
ha-ezviz in HA core.

### ISSUE THREAD

**Issue by joe-pete** [RenierM26/ha-ezviz#51]
Hi RanierM26 I understood that the RanierM26/ha-ezviz version is for just hass.io NOT for Home Assistant Core. Am I right ? Do you plan to release it for CORE as well. If yes, what is your plan. 
Regards, Giuseppe.

**Comment by RenierM26** [comment]
Hi @joe-pete,

It should work for both just like any integration. I'm busy with a pull request to update the "official built in" version.
