### ISSUE TITLE
Services - Privacy mode

### ISSUE THREAD

**Issue by keimaster** [RenierM26/ha-ezviz#52]
When first starting to use the Ezviz integration there was other services that seems to later have been removed. One of those is the option to set the camera in privacy mode i.e. when at home. Could this be added back in, or am I missing something?

**Comment by RenierM26** [comment]
Hi @keimaster ,

All cameras have switch entities. You can just set the privacy switch to on or off.

**Comment by keimaster** [comment]
I feel like an idiot... I suspect that I did not get the transition, and never realized that it was now a switch entity. Thank you so much for helping our, and a great integration for Home Assistant :)

**Comment by RenierM26** [comment]
It's a pleasure to be of assistance.
