### ISSUE TITLE
apiisgp.ezvizlife.com

### ISSUE THREAD

**Issue by nguyenbabao** [RenierM26/ha-ezviz#54]
not work for me ?
![image](https://user-images.githubusercontent.com/68863522/113531666-8cfe4e00-95f3-11eb-9939-71d74de4b486.png)
![image](https://user-images.githubusercontent.com/68863522/113531690-9edff100-95f3-11eb-8c19-66b2727429d9.png)
![image](https://user-images.githubusercontent.com/68863522/113531696-a69f9580-95f3-11eb-8f64-826e3bd76fa3.png)

**Comment by RenierM26** [comment]
Hi @nguyenbabao ,

Do you see anything in the logs? Could you also please try running pyezviz (the api) iteself?

docker exec -it homeassistant /bin/bash
pyezviz -u username@domain -p Password -r apiisgp.ezvizlife.com devices status 

-u your ezviz username
-p your ezviz password

**Comment by nguyenbabao** [comment]
> Hi @nguyenbabao ,
> 
> Do you see anything in the logs? Could you also please try running pyezviz (the api) iteself?
> 
> docker exec -it homeassistant /bin/bash
> pyezviz -u username@domain -p Password -r apiisgp.ezvizlife.com devices status
> 
> -u your ezviz username
> -p your ezviz password

Sorry, this is my fault. because I accidentally enabled "access config".

**Comment by RenierM26** [comment]
No problem. Thank you for the feedback.
