### ISSUE TITLE
C3A (and possibly other battery cams) require to be waked up

### ISSUE THREAD

**Issue by AlbertoLopSie** [RenierM26/ha-ezviz#6]
After a lot of struggle, I managed to configure a C3A camera. To be able to open the RTSP (554) port, you first have to wake it up. I Discovered this at first using the ezvizlife.com service and the realized you have a service call to do that.

Is it possible to auto wake-up the cam on Play?

**Comment by RenierM26** [comment]
Hi AlbertoLopSie,

I make use of a picture-glance card and make use of a tap_action to wake the cam. I then just click on the "unavailable" image that hassio displays and a few seconds later the picture comes up. It will remain streaming until you navigate away from the page.

  - type: picture-glance
    title: Front Door (Live)
    image: 'https://demo.home-assistant.io/stub_config/kitchen.png'
    entities:[]
    camera_image: camera.front_door_camera
    tap_action:
      action: call-service
      service: ezviz_cloud.ezviz_wake_device
      service_data:
        entity_id: camera.front_door_camera

**Comment by AlbertoLopSie** [comment]
Thank you Renier!   It worked!
