### ISSUE TITLE
No setup function defined.

### ISSUE THREAD

**Issue by Slooti** [RenierM26/ha-ezviz#60]
Hi, since todays update, my cameras have gone and I'm getting this error in my HA.

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 21:45:39 (1 occurrences)
Last logged: 21:45:39

Setup failed for ezviz_cloud: No setup function defined.

Can you help with this please? Thanks a lot and best regards

**Comment by RenierM26** [comment]
Hi @Slooti ,

Someone else also reported this error and managed to fix it by updating to the latest version and restarting Home assistant.

1) Double check your on the latest version. Under HACS -> Integrations -> Ezviz Cloud -> Click on the three dots -> Click on "update information".

2) Click update if you get a notice that your're not on the latest version.

3) Restart Home Assistant.

**Comment by Slooti** [comment]
Hi @RenierM26 

Thanks a lot, that fixed the issue. Important to clear the cache again after updating!

cheers

Martin
