### ISSUE TITLE
RTSP stream missing for C3X Uncaught InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source

### ISSUE THREAD

**Issue by Pho3niX90** [RenierM26/ha-ezviz#61]
AS the title suggests, the rtsp stream is missing. 

Config setup
![image](https://user-images.githubusercontent.com/7858187/114923143-bf4a4f80-9e2c-11eb-909e-e7fe15c0f6dc.png)

Error from logs when trying to view the camera live

`Logger: frontend.js.latest.202104073
Source: components/system_log/__init__.py:190
First occurred: 20:50:02 (1 occurrences)
Last logged: 20:50:02

http://10.0.0.141:8123/frontend_latest/chunk.cf277186969c7b147807.js:2:145490 Uncaught InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.`

**Comment by RenierM26** [comment]
Hi @Pho3niX90 ,

Have you perhaps tried to stream the rtsp via VLC player? Could be that your camera requires additional config for the RTSP stream to work.

rtsp:/admin:verificationcodeonbottomofcam@x.x.x.x/h264_stream

If this works, then you can add "/h264_stream" to the "ffmpeg arguments" under the integration options for the camera. (under the specific camera entity)

**Comment by Pho3niX90** [comment]
@RenierM26 it works flawlessly in VLV player. That being said, with the new HA update I made use of their integration of ezviz cloud, and it works flawlessly there as well.

**Comment by RenierM26** [comment]
Hi @Pho3niX90,

This is the exact same code with services and other updates. (The current hass integration comes from this code)

I suspect it's some or other hass issue as it look like a front end problem.
