### ISSUE TITLE
problem with RTSP stream after upgrade C1C to firmware 5.3.2 build 210312

### ISSUE THREAD

**Issue by marcob79** [RenierM26/ha-ezviz#65]
after upgrading my previously working ezviz c1c with firmware v5.3.2 build 210312, the RTSP stream seems not working anynore in home assistant.
i saw this log, but I'm not sure it is really related to this problem

> Logger: custom_components.ezviz_cloud
> Source: custom_components/ezviz_cloud/__init__.py:71
> Integration: Ezviz (documentation)
> First occurred: 4:55:33 PM (1 occurrences)
> Last logged: 4:55:33 PM
> 
> Unable to connect to Ezviz service: A Invalid URL or Proxy error occured

**Comment by RenierM26** [comment]
You can get the pagelist file by following instructions below. Please just remove any confidential info before posting it. (Camera serial, encrypted password etc)

You should be able to open this page in IE or Safari. Is should automatically start downloading a .json file.

https://apiieu.ezvizlife.com/v3/userdevices/v1/resources/pagelist?groupId=-1&limit=30&offset=0&filter=CLOUD%2CTIME_PLAN%2CCONNECTION%2CSWITCH%2CSTATUS%2CWIFI%2CNODISTURB%2CKMS%2CP2P%2CTIME_PLAN%2CCHANNEL%2CVTM%2CDETECTOR%2CFEATURE%2CUPGRADE%2CVIDEO_QUALITY%2CQOS

**Comment by marcob79** [comment]
After upgrading home assistant, I removed custom component and configured
again as integrated component. Now is working back.
I think we can close this ticket

Il sab 8 mag 2021, 13:03 RenierM26 ***@***.***> ha scritto:

**Comment by RenierM26** [comment]
Thank you for the feedback.

**Comment by ahmed-bourenane** [comment]
hello i lost the QR code of my C1C Mini can you help me ?
