### ISSUE TITLE
No services to ptz my camera

### ISSUE THREAD

**Issue by ZainAjam** [RenierM26/ha-ezviz#68]
I have a ezviz c3cn camera. I've set up the ezviz integration from hassio integration and I've configured my account and my camera and a stack of entities (as switches and sensors) are detected automatically, but I have no services or command to pan or tilt the camera. I know the previous hacs integration had ezviz cloud services with a ptz command but this hassio integration has none

**Comment by RenierM26** [comment]
Hi @ZainAjam,

You might have picked the wrong integration. After the latest update there should be two when adding the integation, try the other one.

**Comment by RenierM26** [comment]
Hi @ZainAjam,

I have renamed the component to "Ezviz(Beta)" to avoid confusion with the official hass component. (In Latest release)
