### ISSUE TITLE
Unexpected error fetching ezviz_cloud data: local variable 'json_result' referenced before assignment

### ISSUE THREAD

**Issue by defusiondev** [RenierM26/ha-ezviz#7]
Hi, I've installed ezviz_cloud via HACS and then added the integration via Configuration > Integrations. I've then added my config to configuration.yaml, eg:

ezviz_cloud:
  cameras:
    D91157661:
      username: admin
      password: XXXXXX

after restarting HA i get the following "ERROR" in the logs:

Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:31
Integration: Ezviz Cloud (documentation)
First occurred: 20:49:25 (9 occurrences)
Last logged: 20:56:39

Unexpected error fetching ezviz_cloud data: local variable 'json_result' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 39, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 31, in _update_data
    cameras = self.EzvizClient.load_cameras()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 262, in load_cameras
    camera.load()
  File "/usr/local/lib/python3.8/site-packages/pyezviz/camera.py", line 16, in load
    self._device = self._client._get_deviceinfo(self._serial)
  File "/usr/local/lib/python3.8/site-packages/pyezviz/client.py", line 173, in _get_deviceinfo
    if not json_result:
UnboundLocalError: local variable 'json_result' referenced before assignment

I left the region to "eu", I am located in South Africa - should I have chosen "za"?

**Comment by RenierM26** [comment]
Hi There, 

I'm also located in South africa and make use of the eu endpoint. This looks like a time out problem and might be your internet connection. The device sensitivity queries the actual device and if the response takes too long this might happen. (The query is slow when the device is sleeping as well)  

Have you tried running the py-ezviz python script to see if you get a result? You can find it under:
https://github.com/RenierM26/py-ezviz

pip install py-ezviz
pyezviz -u username -p password devices status

**Comment by defusiondev** [comment]
hi Renier - thanks for the response.

I've installed pyezviz and run it with -d and I can see it logging and then when it reaches this it dies:

DEBUG:urllib3.connectionpool:https://ieu.ezvizlife.com:443 "GET /camera/cameraAction!findAllDevices.action HTTP/1.1" 200 14
local variable 'json_result' referenced before assignment

I'm on 50/25 fibre. 
This is to a remote camera (not on local network) - I have the RTSP stream ports opened (not default ports) on the remote system which is on 20/20 fibre. 
The camera is also shared to the account I am logging in on. 

Time from my running the pyezviz command to this error happening is 4 seconds.

**Comment by defusiondev** [comment]
Just an update, I echo'd the json returned in client.py and the device list is empty when it's accessing a shared account. I got the main user login and now it works. 

Also I see it uses the local IP so it won't work for a remote scenario.

**Comment by RenierM26** [comment]
Thank you for the feedback. I'll add that to the readme.
