### ISSUE TITLE
ezviz_wake_device service missing

### ISSUE THREAD

**Issue by AlbertoLopSie** [RenierM26/ha-ezviz#72]
Hi,
Recently upgraded to the last Ezviz integration (through the official integration, not HACS) and after removing old (HACS) integration, installing the new one and configuring all my cameras again discover that the service `ezviz_wake_device` no longer works.

With my previous version (0.0.2.1   Sorry!  a little old) I used to call it like:
```
  service: ezviz_cloud.ezviz_wake_device
  service_data:
    entity_id: camera.playa
```

The repo [contains a definition](https://github.com/RenierM26/ha-ezviz/search?q=wake_device) for a new service `wake_device` but I cannot call it from my HA (2021.5.5)

Any hint?

**Comment by AlbertoLopSie** [comment]
Well... I don't know if it's a bug or not...

Deleted "Official" integration and installed the HACS one. Now it works as expected and the service `ezviz_cloud.ezviz_wake_device` exists again.

**Comment by RenierM26** [comment]
Hi @AlbertoLopSie,

The component has the same name as the official one. This causes some confusion so I have renamed it in the latest release.

The name change won't break anything.

Thanks.
