### ISSUE TITLE
C8C motion trigger not working if Alarm Notification set to "Human Shape Detection"

### ISSUE THREAD

**Issue by gadgetchnnel** [RenierM26/ha-ezviz#79]
The C8C has two options under Alarm Notification for the type of motion which triggers a notification:

* Human Shape Detection (the default)
* Image Change Detection

I prefer "Human Shape Detection" (as there are less false alerts) but the motion trigger binary sensor never triggers in this mode. It only works when the "Image Change Detection" option is selected.

The last alarm picture and last alarm time sensors are also not updated in "Human Shape Detection" mode, so I can't use those.

Is there a way to get this to work in this mode?
Currently I'm working around this by using the notification sensor from the Home Assistant app to pick up when there's a notification from the Ezviz app, but it's not always reliable.

**Comment by gadgetchnnel** [comment]
I did some testing with the code in the pyEzviz module and found that this appears to be because **get_alarminfo** in client.py sends  "stype": 2401 to the API, which appears to make it filter on just "Motion Detection Alarm" events and not include "Intelligent Detection Alarm" events.

Passing "stype": -1 instead causes it to pick up any alarm events.
I've not been able to work out what would need to be sent to just filter on "Motion Detection Alarm" and "Intelligent Detection Alarm" events.

**Comment by lquist** [comment]
I run into the same issue with the CTQ3N when the camera is set to "human shape detection". Although get_alarminfo in client.py is set to "stype": -1 as mentioned above, HA motion trigger doesn't activate. Setting the camera to "image change detection" it triggers properly. Any ideas or suggestions?
