### ISSUE TITLE
Ezviz Alarm no longer available in 0.0.7.0?

### ISSUE THREAD

**Issue by francois-dotnet** [RenierM26/ha-ezviz#81]
I noticed that since 20 June, probably after I updated the component in HACS, I no longer have an alarm control panel entity for Ezviz and the arm and disarm service calls are not working?
Anyone else? Is this a bug, is there a work around? 
Using 0.0.7.0

**Comment by RenierM26** [comment]
Hi @francois-dotnet,

Apologies for the delay, was out of order for a while with COVID. With all the Hassio patches I somehow removed the platform from init. It should work now with v0.0.7.1

**Comment by francois-dotnet** [comment]
Great thanks! I rolled back and it worked fine. Will update to 0.0.7.1

**Comment by myTselection** [comment]
Hi @RenierM26 ,
After update, the Ezviz alarm panel didn't appear. Also tried to remove Ezviz integration, restart HA and add Ezviz integration again, but still the alarm panel didn't appear. I used to have the alarm panel with < 0,7 versions.
Would appreciate if you could take another look into this.

Thanks a lot anyway, great integration, very usefull with Ezviz DB1 doorbell!!

**Comment by myTselection** [comment]
Hi @RenierM26 , I see many efforts to get the alarm panel back, thanks a lot for that! Yet I need to report that still in v 0.0.7.7 it's still not working. Any workaround would be appreciated.
