### ISSUE TITLE
Ezviz Alarm no longer available since 0.0.7.0

### ISSUE THREAD

**Issue by myTselection** [RenierM26/ha-ezviz#89]
I noticed that since 20 June, probably after I updated the component in HACS, I no longer have an alarm control panel entity for Ezviz and the arm and disarm service calls are not working since v 0.0.7.0. 
Different efforts have been taken to make the alarm panel available again, 
see also previously closed #81 , but which didn't seem to be resolved.

**Comment by RenierM26** [comment]
Hi @myTselection,

The last update restores the "last state" of the alarm platform. An invalid last state causes the Alarm platform to show as unavailable.

Please set the status once from the dev tools to fix this permanently.

![image](https://user-images.githubusercontent.com/66512715/134765715-0c1f4c31-de62-4019-92b6-5a2f83b60c9e.png)

**Comment by myTselection** [comment]
Ezviz alarm is not available anymore since 0.0.7.0, also if eziviz is re-created after HA restart. So I can't set any state of it.

**Comment by RenierM26** [comment]
Hi @myTselection,

Are you using the correct integration? This one has the label Ezviz (Beta). If you're using the official hass integration then the alarm won't be available.

Could you please double check?

**Comment by myTselection** [comment]
😳 sorry, indeed with the ezviz beta the alarm panel does appear correctly. Sorry, my mistake!
