### ISSUE TITLE
Error for camera not supporting alarm schedules

### ISSUE THREAD

**Issue by powro** [RenierM26/ha-ezviz#97]
Logger: custom_components.ezviz_cloud.coordinator
Source: custom_components/ezviz_cloud/coordinator.py:32 
Integration: Ezviz(Beta) 
First occurred: 21:32:48 (7 occurrences) 
Last logged: 21:37:00

Unexpected error fetching ezviz_cloud data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 38, in _async_update_data
    return await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ezviz_cloud/coordinator.py", line 32, in _update_data
    return self.ezviz_client.load_cameras()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/client.py", line 433, in load_cameras
    self._cameras[device] = EzvizCamera(self, device, data).status()
  File "/usr/local/lib/python3.9/site-packages/pyezviz/camera.py", line 136, in status
    "alarm_schedules_enabled": self._is_alarm_schedules_enabled(),
  File "/usr/local/lib/python3.9/site-packages/pyezviz/camera.py", line 105, in _is_alarm_schedules_enabled
    _alarm_schedules = [
TypeError: 'NoneType' object is not iterable

**Comment by RenierM26** [comment]
Hi @powro,

Please try the latest release v0.0.8.8

It should fix this problem.

**Comment by powro** [comment]
The previous error is fine now, but git other instead. Probably not related, but cannot verify the fix because of this. There are no details to find out the root cause.

Logger: custom_components.ezviz_cloud
Source: custom_components/ezviz_cloud/__init__.py:131 
Integration: Ezviz(Beta) 
First occurred: 08:12:15 (12 occurrences) 
Last logged: 08:22:54

Unable to connect to Ezviz service:

**Comment by RenierM26** [comment]
Hi @powro,

Did you update to v0.0.8.9 or v0.0.8.8 ? I missed something in the 0.0.8.8 release that could cause auth errors and quickly fixed and published a new release (0.0.8.9)

Sorry about all the releases but I'm busy adding support for 2FA/MFA.

**Comment by powro** [comment]
I have updated to 0.0.8.9.

**Comment by RenierM26** [comment]
Hi @powro,

Could you perhaps run this from a workstation/laptop with python installed?

pip install pyezviz
python -m pyezviz -d -u user@domain.com -p Pass@ devices status

The debug output might give me a clue as to what the issue is.

**Comment by powro** [comment]
Sure. Will try a bit later today and share here. Thank you for a great support! This issue started to happen after upgrade from 0.0.8.1 or something around that version.

**Comment by powro** [comment]
Devices status query completes successfully without any error with login. Looks like its the same issue reported under #98.

**Comment by RenierM26** [comment]
Hi @powro,

I think I found the problem. If a region redirect occurs, the session header is cleared and not set again. 

I'm busy with a fix.

**Comment by RenierM26** [comment]
Hi @powro,

Think I found the problem. Could you please test 0.0.9.0?

**Comment by powro** [comment]
Tested. Works great. Thank you!
