### ISSUE TITLE
Error in EzViz Cloud login with lastest versions 0.0.8.8 and 0.0.8.9

### ISSUE THREAD

**Issue by Gferretta** [RenierM26/ha-ezviz#98]
Hi.

With 0.0.8.7 no problems at all.

But when updated, no login in EzViz Cloud.

Rollback to 0.0.8.7 and all working again (all cameras are fine)

No internet problem.

ADDED: With 0.0.8.8 occurs the same error and NO login in EzViz Cloud.     Only work with 0.0.8.7   :( 

![EzViz error 1](https://user-images.githubusercontent.com/65413059/142732172-669b908d-1511-4bda-8023-c84bf02b4eab.jpg)

**Comment by RenierM26** [comment]
Hi @Gferretta ,

Think I found the problem. Could you please test 0.0.9.0?

**Comment by Gferretta** [comment]
> Hi @Gferretta ,
> 
> Think I found the problem. Could you please test 0.0.9.1?
> 

With 0.0.9.1 working again!!!

Thanks a lot.

Regards
